name: cache
author: nienbo-actions
description: S3 Cache Action with actions/cache@v2 fallback
inputs:
  endpoint:
    description: S3 Endpoint without Region
    required: false
    default: s3.amazonaws.com
  region:
    description: S3 Region
    required: false
    default: us-east-2
  port:
    description: S3 Server Port
    required: false
  insecure:
    description: Use http only connection
    required: false
  aws-access-key:
    description: S3 AWS_ACCESS_KEY_ID
    required: true
  aws-secret-access-key:
    description: S3 AWS_SECRET_ACCESS_KEY
    required: true
  bucket:
    description: S3 Bucket Name
    required: true
  path:
    description: 'A list of files, directories, and wildcard patterns to cache and restore'
    required: true
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring the cache if no cache hit occurred for key'
    required: false
  use-fallback:
    description: 'Use official GitHub actions/cache@v2 as fallback'
    required: false
    default: 'false'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: node12
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
branding:
  icon: 'archive'
  color: 'gray-dark'
